======================== MIGRATION: Quiz AI Feature ========================
-- File ini berisi optional SQL untuk meningkatkan struktur database guna mendukung fitur Quiz AI yang lebih baik

-- 1. Tambahkan kolom baru ke user_activity_log jika belum ada (untuk quiz details)
ALTER TABLE user_activity_log 
ADD COLUMN IF NOT EXISTS type VARCHAR(20) DEFAULT 'activity' AFTER score_performance,
ADD COLUMN IF NOT EXISTS title VARCHAR(255) DEFAULT NULL AFTER type,
ADD COLUMN IF NOT EXISTS quiz_details JSON DEFAULT NULL AFTER summary;

-- 2. (OPSIONAL) Buat tabel terpisah untuk quiz results dengan detail lebih lengkap
CREATE TABLE IF NOT EXISTS quiz_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    activity_log_id INT NOT NULL,
    quiz_topic VARCHAR(255) NOT NULL,
    score INT NOT NULL,
    total_questions INT NOT NULL DEFAULT 5,
    percentage FLOAT NOT NULL DEFAULT 0,
    details JSON DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (activity_log_id) REFERENCES user_activity_log(id) ON DELETE CASCADE,
    INDEX idx_user_date (user_id, created_at),
    INDEX idx_topic (quiz_topic)
);

-- 3. Insert aktivitas default untuk Quiz AI jika belum ada
INSERT IGNORE INTO activities (id, title, type, content_url, style_target) 
VALUES (999, 'Quiz AI Generated', 'quiz', 'Generated by Gemini AI', 'reading');

-- ======================== CONTOH DATA ========================
-- Setelah migration ini dijalankan, data quiz akan disimpan dengan struktur:
-- user_activity_log: 
--   - type: 'quiz'
--   - title: 'Quiz AI: Topik Pembelajaran'
--   - score_performance: persentase skor (0-100)
--   - quiz_details: JSON berisi detail jawaban lengkap

-- quiz_results (opsional):
--   - Menyimpan detail quiz secara terpisah untuk kemudahan query dan analisis
--   - Memudahkan tracking progress user per topik
